namespace Account_Service.Models.DTO
{
    // Data Transfer Object (DTO) representing a transporter entity
    public class TransporterDTO
    {
        // Unique identifier for the user, typically generated by the database or authentication system
        public string UserId { get; set; }

        // The name of the transporter or user
        public string Name { get; set; }

        // The email address of the transporter
        public string Email { get; set; }

        // Represents the role of the user, such as "Transporter", "Admin", etc.
        public string Role { get; set; }  // Include the role information

        // The date and time when the transporter was created, set during registration or user creation
        public DateTime CreatedAt { get; set; }
    }
}
